Alg 8
ulanovtrip/algorithms pull request #11
Opened 2020-10-13 07:55 UTC by ulanovtrip

13/10/2020 10:54 AM

Правки: 
Решено: 70, 71, 72

2020-10-14 07:31 UTC, novpeter requested changes

2020-10-14 07:31 UTC, novpeter commented on src/petrs/analysis/Task_51.java
> +        int firstMinimum = numbers[0];
Решение в лоб. Но можно сделать все за один цикл, взяв две переменные `firstMin` и `secondMin`

2020-10-14 07:31 UTC, novpeter commented on src/petrs/analysis/Task_52.java
> +        for (int i = 0; i < numbers.length; i++) {
Избыточен двойной цикл. У тебя отсортированный массив, значит повторяющиеся элементы стоят рядом. Тебе нужно одним циклом пройтись по массиву

2020-10-14 07:31 UTC, novpeter commented on src/petrs/IntegerArray.java
> +    public void arrayForTask48() {
Не выноси все подряд в утилиты. Создание массива для задачи должно быть в самой задаче. Ты эти функции не будешь переиспользовать в отличии от рандомного генератора массива

2020-10-14 07:31 UTC, novpeter commented on src/petrs/analysis/Task_55.java
> +            if (inputArray[i] > inputArray[i + 1]) {
Ты сравниваешь на убывание этой строчкой, что приводит к неправильному решению

2020-10-14 07:31 UTC, novpeter commented on src/petrs/converting_an_array/Task_56.java
> + */
Тут может быть задача с подвохом. Каждый раз, когда ты меняешь число больше данного, среднее ариф меняется

2020-10-14 07:31 UTC, novpeter commented on src/petrs/converting_an_array/Task_62.java
> +        for (int i = 0; i < inputArray.getSize(); i++) {
У тебя в итоге остался сортированный массив. Можно сделать следующее:
1. Взять сортированную копию массива
2. Пройтись по нему и положить в сет все неуникальные числа
3. Отсортировать массив циклом так, чтобы i элемент не находился в сете неуникальных чисел

2020-10-14 07:31 UTC, novpeter commented on src/petrs/converting_an_array/Task_65.java
> +        if (inputArray.getSize() == 0) {
Очень хороший подход

2020-10-14 07:31 UTC, novpeter commented on src/petrs/converting_an_array/Task_71.java
> + * что их сумма равна сумме каких-либо трех элементов второго массива.
Задача похожа на динамическое программирование. Лучше погуглить

2020-10-14 07:31 UTC, novpeter commented on src/petrs/converting_an_array/Task_66.java
> +        IntegerArray B = new IntegerArray(A.getSize(), band);
Можно сделать одним циклом

2020-10-14 07:32 UTC, novpeter approved these changes

2020-10-14 08:05 UTC, ulanovtrip commented on src/petrs/analysis/Task_51.java
> +        int firstMinimum = numbers[0];
Сделал.

2020-10-14 08:13 UTC, ulanovtrip commented on src/petrs/analysis/Task_52.java
> +        for (int i = 0; i < numbers.length; i++) {
Сделал.

2020-10-14 08:19 UTC, ulanovtrip commented on src/petrs/IntegerArray.java
> +    public void arrayForTask48() {
Всё проще, я такие методы создавал для тестов, так что просто удалил их все заменив на random.

2020-10-14 08:44 UTC, ulanovtrip commented on src/petrs/analysis/Task_55.java
> +            if (inputArray[i] > inputArray[i + 1]) {
Переделал.

2020-10-14 09:12 UTC, ulanovtrip commented on src/petrs/converting_an_array/Task_56.java
> + */
Не понял твоего замечания. Попробовал менять данное число в разные стороны.
С чего вдруг меняется среднее арифметическое?
Массив у меня один и тот же.

2020-10-14 09:16 UTC, novpeter commented on src/petrs/converting_an_array/Task_56.java
> + */
Забей)

2020-10-15 06:40 UTC, ulanovtrip commented on src/petrs/converting_an_array/Task_62.java
> +        for (int i = 0; i < inputArray.getSize(); i++) {
Непонятно что это даст.
Плюс идею я не понимаю.

2020-10-15 06:46 UTC, ulanovtrip commented on src/petrs/converting_an_array/Task_66.java
> +        IntegerArray B = new IntegerArray(A.getSize(), band);
Переделал.

2020-10-15 06:47 UTC, ulanovtrip commented on src/petrs/converting_an_array/Task_65.java
> +        if (inputArray.getSize() == 0) {
Спасибо

2020-10-15 07:02 UTC, ulanovtrip commented on src/petrs/converting_an_array/Task_71.java
> + * что их сумма равна сумме каких-либо трех элементов второго массива.
Я погуглил.
Нашел пару ссылок по такой задаче https://www.cyberforum.ru/cpp-beginners/thread2543331.html
Но выглядит жутким.

2020-10-15 07:32 UTC, ulanovtrip commented on src/petrs/converting_an_array/Task_71.java
> + * что их сумма равна сумме каких-либо трех элементов второго массива.
Почитал https://habr.com/ru/post/423939/
Хз, не понял как это может быть связано.

2020-10-15 07:52 UTC, novpeter commented on src/petrs/converting_an_array/Task_62.java
> +        for (int i = 0; i < inputArray.getSize(); i++) {
Ты отсортировал и удалил. На выходе у тебя получится отсортированный массив без повторяющихся элементов 
А тебе надо вернуть в том же порядке, но без повторяющихся элементов

2020-10-15 08:43 UTC, ulanovtrip commented on src/petrs/converting_an_array/Task_62.java
> +        for (int i = 0; i < inputArray.getSize(); i++) {
Теперь понял.

2020-10-16 05:34 UTC, ulanovtrip commented on src/petrs/converting_an_array/Task_62.java
> +        for (int i = 0; i < inputArray.getSize(); i++) {
Сделал как Вы просили.

2020-10-16 06:19 UTC, novpeter approved these changes

2020-10-16 06:32 UTC, merged