Alg 10
ulanovtrip/algorithms pull request #12
Opened 2020-10-27 07:18 UTC by ulanovtrip

2020-10-27 10:50 UTC, novpeter requested changes

2020-10-27 10:50 UTC, novpeter commented on src/petrs/converting_an_array/Task_79.java
> +        for (int i = 0; i < output.length - 4; i++, outputIndex++) {
Почему `-4`?

2020-10-29 08:34 UTC, ulanovtrip commented on src/petrs/IntegerArray.java
> +    public int getIndex(int value) {
Думаешь он там внутри как-то по-другому реализован?

2020-10-29 08:54 UTC, ulanovtrip commented on src/petrs/converting_an_array/Task_79.java
> +        for (int i = 0; i < output.length - 4; i++, outputIndex++) {
Можем разобрать эту задачу?
Долго сидел, не понял как покрыть все кейсы.

2020-10-29 08:55 UTC, novpeter commented on src/petrs/converting_an_array/Task_79.java
> +        for (int i = 0; i < output.length - 4; i++, outputIndex++) {
Лучше при встрече

2020-10-29 08:56 UTC, novpeter commented on src/petrs/IntegerArray.java
> +    public int getIndex(int value) {
По крайней мере, если элемента нет, он должен вернуть `-1`

2020-10-29 09:01 UTC, ulanovtrip commented on src/petrs/converting_an_array/Task_79.java
> +        for (int i = 0; i < output.length - 4; i++, outputIndex++) {
Я продолжаю решать, может получится. Но решение костыльное просто. Погуглю.

2020-10-29 09:06 UTC, ulanovtrip commented on src/petrs/IntegerArray.java
> +    public int getIndex(int value) {
Сделал

2020-11-11 09:21 UTC, merged