17/09/2020 11:34 AM
ulanovtrip/algorithms pull request #2
Opened 2020-09-17 08:35 UTC by ulanovtrip

Tasks: 35, 36, 37, 38

2020-09-18 09:32 UTC, novpeter requested changes

2020-09-18 09:32 UTC, novpeter commented on src/petrs/analysis/Task_35.java
> +            if (i == 0) smallestEvenElement = inputArray.getElement(i);
Проблема возникнет при пустом массиве
Логика должна быть следующей:
1. Проверка массива кол-во элементов. Если он пустой, выкинуть ошибку
2. Далее идти по массиву и проверять каждый элемент на четность и сравнивать с текущим. Если условия выполняются - обновляй smallestEvenElement

2020-09-18 09:32 UTC, novpeter commented on src/petrs/analysis/Task_35.java
> +            if (i == 0) smallestEvenElement = inputArray.getElement(i);
Также если у тебя массив будет состоять из нечетных чисел, программа должна выкинуть ошибку. Делай алгоритм в отдельном методе и вызывай его в `main(String[] args)` передавая в метод рандомный массив

2020-09-18 09:32 UTC, novpeter commented on src/petrs/analysis/Task_36.java
> +        }
Та же самая проблема: не проверяется массив на кол-во элементов. Не обработан кейс, когда нет чисел кратных трем на нечетных позициях

2020-09-20 13:47 UTC, ulanovtrip commented on src/petrs/analysis/Task_35.java
> +            if (i == 0) smallestEvenElement = inputArray.getElement(i);
Это сделал.

2020-09-20 14:59 UTC, novpeter commented on src/petrs/analysis/Task_35.java
> +            if (i == 0) smallestEvenElement = inputArray.getElement(i);
Не вижу

2020-09-21 10:18 UTC, merged